logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    nodeValue: error
    org:
      springframework: trace
      hibernate:
        SQL: debug
    root: info

server:
  port: '8081'

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SYSTEM
    password: 43397275
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '600000'